name: Build Marp presentation

on:
  push:
    branches: ["main"] # запускать при коммитах в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build presentation
        run: marp slides.md -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
